import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import EffectButton from '../components/effectButton'
import PowerButton from '../components/PowerButton'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [effect1,setEffect1]=useState(false);
  const [effect2,setEffect2]=useState(false);
  const [effect3,setEffect3]=useState(false);
  const [effect4,setEffect4]=useState(false);
  const [effectOn,setEffectOn]=useState(0);
  const [power,setPower]=useState(false);

  function toggleEffects(effect:number){
    if(effect==-1){
      setEffect1(true)
      setEffectOn(1)
    }
      
    else if(power)
    {
      switch (effectOn) {
        case 1:
            setEffect1(false);
          break;
        case 2:
          setEffect2(false);
          break;
        case 3:
          setEffect3(false);
          break;
        case 4:
          setEffect4(false);
          break;
      
        default:
          break;
      }
      if(effect!=effectOn)
      {
        switch (effect) {
          case 1:
              setEffect1(true);
            break;
          case 2:
            setEffect2(true);
            break;
          case 3:
            setEffect3(true);
            break;
          case 4:
            setEffect4(true);
            break;
        
          default:
            break;
      }
      setEffectOn(effect)
      }
      else
        setEffectOn(0)
    }
      
  }
  function tooglePower(){
    var p= power
    if(!p)
    {
      setPower(!p)
      toggleEffects(-1) 
    }
    else
    {
      toggleEffects(0)
      setPower(!p)
    }
      
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Luzes de Natal
        </h1>
        <div style={{display:'flex',flexDirection:'row',width:'80vw',justifyContent:'space-around'}}>
          <EffectButton changefc={toggleEffects} number={1} toggle={effect1} title={"Efeito 1"}/>
          <EffectButton changefc={toggleEffects} number={2} toggle={effect2} title={"Efeito 2"}/>
          
        </div>
        <PowerButton changefc={tooglePower} number={effectOn} toggle={power}/>
        <div style={{display:'flex',flexDirection:'row',width:'80vw',justifyContent:'space-around'}}>
          <EffectButton changefc={toggleEffects} number={3} toggle={effect3} title={"Efeito 3"}/>
          <EffectButton changefc={toggleEffects} number={4} toggle={effect4} title={"Efeito 4"}/>
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/28rodrigo/"
          target="_blank"
          rel="noopener noreferrer">
          Powered by Rodrigo Pereira @ 2022
        </a>
      </footer>
    </div>
  )
}
